<?php

namespace AppBundle\Repository;

/**
 * BanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanRepository extends \Doctrine\ORM\EntityRepository
{
    public function clean()
    {
        $this->_em
            ->createQuery("
                DELETE AppBundle:Ban b
                WHERE b.timestamp + 86400 < :now
            ")
            ->setParameter('now', time())
            ->execute()
        ;
    }
}
