<?php

namespace AppBundle\Repository;

/**
 * IpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IpRepository extends \Doctrine\ORM\EntityRepository
{
}
