<?php

namespace DigiLoginBundle\Repository;

/**
 * DigiLoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DigiLoginRepository extends \Doctrine\ORM\EntityRepository
{
}
