parameters:
    base.locale.listener.class: BaseBundle\EventListener\LocaleListener
    base.last_route.listener.class: BaseBundle\EventListener\LastRouteListener

services:

    base.locale.listener:
        class: '%base.locale.listener.class%'
        arguments:
            - '%kernel.default_locale%'
        tags:
            - { name: kernel.event_subscriber }

    base.last_route.listener:
        class: '%base.last_route.listener.class%'
        arguments:
            - '@base.routing.helper'
        tags:
            - { name: kernel.event_subscriber }
