parameters:
    base.oauth_user_provider.class: BaseBundle\Provider\OAuthUserProvider
    hwi_oauth.account.connector.class: BaseBundle\Connect\AccountConnect
    pagerfanta.view.light.class: BaseBundle\Pagerfanta\View\LightView
    pagerfanta.template.light.class: BaseBundle\Pagerfanta\Template\LightTemplate

services:

    base.oauth_user_provider:
        class: '%base.oauth_user_provider.class%'
        arguments:
            - '@doctrine.orm.entity_manager'

    hwi_oauth.account.connector:
        class: '%hwi_oauth.account.connector.class%'

    pagerfanta.view.light:
        class: '%pagerfanta.view.light.class%'
        public: false
        arguments: ['@pagerfanta.template.light']
        tags:
            - { name: pagerfanta.view, alias: light }

    pagerfanta.template.light:
        class: '%pagerfanta.template.light.class%'
        public: false
        arguments: ['@translator']

